const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');
const fs = require('fs/promises');
const isDev = !app.isPackaged;

// Sets the app's name as reported to the OS (macOS dock/menu bar, Windows
// taskbar grouping) and — importantly — the default folder name Electron
// uses for app.getPath('userData'), where the custom library files live.
// Must be called before app.whenReady().
app.setName('C4D Visuals');

function createSplash() {
  const splash = new BrowserWindow({
    width: 420,
    height: 420,
    frame: false,
    transparent: true,
    resizable: false,
    movable: false,
    alwaysOnTop: true,
    center: true,
    skipTaskbar: true,
    webPreferences: { contextIsolation: true },
  });
  splash.loadFile(path.join(__dirname, 'splash.html'));
  return splash;
}

function createWindow() {
  const splash = createSplash();
  const splashShownAt = Date.now();
  const MIN_SPLASH_MS = 900; // keep it visible a beat even on a fast load, so it doesn't just flash

  const win = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1200,
    minHeight: 800,
    show: false, // stay hidden until the first real frame is ready, so the splash is what's seen first
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      preload: path.join(__dirname, 'preload.cjs'),
    },
    title: 'C4D Visuals',
    icon: path.join(__dirname, 'build', 'icon.png'),
  });

  win.once('ready-to-show', () => {
    const elapsed = Date.now() - splashShownAt;
    const remaining = Math.max(0, MIN_SPLASH_MS - elapsed);
    setTimeout(() => {
      if (!splash.isDestroyed()) splash.close();
      win.show();
    }, remaining);
  });

  if (isDev) {
    win.loadURL('http://localhost:5173');
    win.webContents.openDevTools();
    // If Electron was started before the Vite dev server finished starting up,
    // retry instead of leaving the splash stuck on a failed load.
    win.webContents.on('did-fail-load', () => {
      setTimeout(() => win.loadURL('http://localhost:5173'), 500);
    });
  } else {
    win.loadFile(path.join(__dirname, 'dist', 'public', 'index.html'));
    win.webContents.openDevTools(); // TEMPORARY — for diagnosing the blank-window issue, remove once resolved
  }
}

// ── Custom library storage ──────────────────────────────────────────────
// Baked controller/keyboard/mouse skins the user saves from the editor are
// written as real files under the app's userData folder, bounded only by
// actual disk space — not the ~5-10MB localStorage quota the renderer would
// otherwise be stuck with. Layout per section (e.g. "body-xbox-one"):
//   <userData>/custom-library/<section>/manifest.json   — [{id, name, filename}]
//   <userData>/custom-library/<section>/<id>.<ext>      — the actual image

function libraryDir(section) {
  // Section strings are always generated by our own code (e.g. "body-xbox-one",
  // "kb-body") — sanitize anyway so a malformed value can't escape the folder.
  const safe = String(section).replace(/[^a-zA-Z0-9_-]/g, '');
  return path.join(app.getPath('userData'), 'custom-library', safe);
}

async function readManifest(dir) {
  try {
    const raw = await fs.readFile(path.join(dir, 'manifest.json'), 'utf-8');
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

async function writeManifest(dir, manifest) {
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf-8');
}

function dataUrlToBuffer(dataUrl) {
  const match = /^data:([^;]+);base64,(.*)$/s.exec(dataUrl);
  if (!match) return null;
  return { mime: match[1], buffer: Buffer.from(match[2], 'base64') };
}

ipcMain.handle('library:load', async (_event, section) => {
  const dir = libraryDir(section);
  const manifest = await readManifest(dir);
  const entries = [];
  for (const item of manifest) {
    try {
      const bytes = await fs.readFile(path.join(dir, item.filename));
      const ext = path.extname(item.filename).slice(1) || 'png';
      entries.push({ id: item.id, name: item.name, url: `data:image/${ext};base64,${bytes.toString('base64')}` });
    } catch {
      // File missing on disk (manually deleted, etc.) — skip it rather than
      // fail the whole library load over one bad entry.
    }
  }
  return entries;
});

ipcMain.handle('library:add', async (_event, section, name, dataUrl) => {
  const decoded = dataUrlToBuffer(dataUrl);
  if (!decoded) return null;
  const dir = libraryDir(section);
  try {
    const manifest = await readManifest(dir);
    const ext = decoded.mime.split('/')[1] || 'png';
    const id = `custom-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
    const filename = `${id}.${ext}`;
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(path.join(dir, filename), decoded.buffer);
    manifest.push({ id, name, filename });
    await writeManifest(dir, manifest);
    return { id, name, url: dataUrl };
  } catch (err) {
    console.error('library:add failed', err);
    return null;
  }
});

ipcMain.handle('library:remove', async (_event, section, id) => {
  const dir = libraryDir(section);
  const manifest = await readManifest(dir);
  const item = manifest.find(m => m.id === id);
  const next = manifest.filter(m => m.id !== id);
  await writeManifest(dir, next);
  if (item) {
    try { await fs.unlink(path.join(dir, item.filename)); } catch { /* already gone — fine */ }
  }
});

app.whenReady().then(() => {
  createWindow();
  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});